### ISSUE TITLE
Running the contributed command:'terminalHere.create' failed.

### ISSUE THREAD

**Issue by mellena1** [Tyriar/vscode-terminal-here#12]
I just downloaded this tool as it seemed super useful. However, I am getting this error whenever I try to use it.

I have narrowed it down to it having problems with finding the vscode npm library. Is there anything I can do to fix this?

**Comment by seqizz** [comment]
I was using the plugin for a long time, and started to fail with this error. Compatibility problem?

//edit: switched to https://github.com/fabiospampinato/vscode-open-in-terminal

**Comment by Tyriar** [comment]
Should be fixed now, thanks for the report
