### ISSUE TITLE
Frequent error has started appearing

### ISSUE THREAD

**Issue by carlca** [Tyriar/vscode-terminal-here#13]
macOS 10.13.2
VSCode 1.20.0 Insiders

I have just updated to the latest version of VSCode Insiders, and I have started to see the error `A system error occurred (ENOENT: no such file or directory, stat '/Users/carlca/.vscode-insiders/extensions/Tyriar.vscode-terminal-here-0.0.5/out/src')` appear on a fairly frequent basis. Do I need to add something to my config or is there some other cause?

Ctrl ` still seems to invoke the terminal ok, although I do recall reading recently that the operation of Terminal Here has changed slightly. Do I need to do something differently? Thanks.

**Comment by Tyriar** [comment]
> Tyriar.vscode-terminal-here-0.0.5

You should update the extension to latest, I can't repro on macOS under 0.1.1
