### ISSUE TITLE
Behave like workbench.action.terminal.focus

### ISSUE THREAD

**Issue by Hackerpcs** [Tyriar/vscode-terminal-here#16]
I use this little trick to be able to switch between terminal and editor
```
    {
        "key": "ctrl+`",
        "command": "workbench.action.terminal.focus"
    },
    {
        "key": "ctrl+`",
        "command": "workbench.action.focusActiveEditorGroup",
        "when": "terminalFocus"
    }
```
With workbench.action.terminal.focus if a terminal isn't open it opens one, if a terminal is open it just switches focus. It would be nice for terminalHere.create to behave similarly

Right now I use this workaround
```
    {
        "key": "ctrl+shift+`",
        "command": "terminalHere.create",
        "when": "editorFocus"
    }
```

**Comment by Tyriar** [comment]
There's no way to do this currently from an extension.
