### ISSUE TITLE
extra return when opening terminal-here with a bash command prompt

### ISSUE THREAD

**Issue by sdwarwick** [Tyriar/vscode-terminal-here#2]
![image](https://cloud.githubusercontent.com/assets/7736675/19561659/9fb60876-96a7-11e6-9216-7d27fe3717a5.png)

this is windows 10, 

{
      "terminal.integrated.shell.windows": "C:\Program Files\Git\bin\bash.exe"
}

**Comment by Tyriar** [comment]
This extension is now deprecate, see https://github.com/Tyriar/vscode-terminal-here/issues/20
