### ISSUE TITLE
Default directory location per project.

### ISSUE THREAD

**Issue by unional** [Tyriar/vscode-terminal-here#3]
I want to configure *per workspace* on where the terminal can start.

The extension currently opens a terminal at the current directory of the opened file.

Another feature to consider is adding a right click menu item on the project panel to start terminal in the selected directory.

**Comment by Tyriar** [comment]
I'm going to close this off in favor of https://github.com/Microsoft/vscode/issues/17387, thanks for bearing with me :smile:

Implementing the right click option is captured here https://github.com/Microsoft/vscode/issues/8132
