### ISSUE TITLE
Suggestion: Introduce optional toggle behaviour

### ISSUE THREAD

**Issue by carlca** [Tyriar/vscode-terminal-here#8]
Hello, is there any chance that the option could be introduced whereby invoking Terminal Here on on existing open terminal simply closed it, in other words making it a toggle operation. Maybe it could be configurable:

"editor.terminal-here": "toggle"/"immediate"

**Comment by Tyriar** [comment]
It's definitely possible to just open one of the terminals that was previously opened. My only concern here is that it might feel a little weird if the cwd was changed after opening it, as VS Code and the extension has no knowledge of the cwd of a terminal after it has been opened.

**Comment by Tyriar** [comment]
This extension is now deprecate, see https://github.com/Tyriar/vscode-terminal-here/issues/20
